export interface CreateMedicineInterface {
  productPrescribed: string;
  productCategory: string;
  productDosage: string;
  practitionerNote: string;
}

export enum DrugClassDescription {
  Analgesics = 'Pain relievers (e.g., Acetaminophen, Ibuprofen)',
  Antibiotics = 'Drugs used to treat bacterial infections (e.g., Amoxicillin, Azithromycin)',
  Anticoagulants = 'Blood thinners (e.g., Warfarin, Heparin)',
  Antidepressants = 'Used to treat depression (e.g., Fluoxetine, Sertraline)',
  Antidiabetics = 'Used to manage diabetes (e.g., Metformin, Insulin)',
  Antihistamines = 'Allergy medications (e.g., Diphenhydramine, Loratadine)',
  Antihypertensives = 'Blood pressure medications (e.g., Lisinopril, Amlodipine)',
  Antipsychotics = 'Used to treat psychiatric conditions (e.g., Olanzapine, Risperidone)',
  Bronchodilators = 'Used to treat respiratory issues like asthma (e.g., Albuterol, Salmeterol)',
  Corticosteroids = 'Used to reduce inflammation (e.g., Prednisone, Hydrocortisone)',
  Diuretics = 'Increase urine output (e.g., Furosemide, Hydrochlorothiazide)',
  Hormones = 'Hormonal treatments (e.g., Estrogen, Testosterone)',
  Immunosuppressants = 'Suppress the immune system (e.g., Cyclosporine, Tacrolimus)',
  Lipid_Lowering_Agents = 'Manage cholesterol levels (e.g., Atorvastatin, Simvastatin)',
  Muscle_Relaxants = 'Reduce muscle spasms (e.g., Baclofen, Cyclobenzaprine)',
  Sedatives_Hypnotics = 'Induce sleep or relaxation (e.g., Zolpidem, Diazepam)',
  Vitamins_Minerals = 'Dietary supplements (e.g., Vitamin D, Iron supplements)',
  Antivirals = 'Used to treat viral infections (e.g., Acyclovir, Oseltamivir)',
  Antifungals = 'Treat fungal infections (e.g., Fluconazole, Terbinafine)',
  Antiemetics = 'Prevent nausea and vomiting (e.g., Ondansetron, Metoclopramide)',
  Anesthetics = 'Local and general anesthetics (e.g., Lidocaine, Propofol)',
  Anthelmintics = 'Treat parasitic worm infections (e.g., Albendazole)',
  Anticholinergics = 'Block the action of acetylcholine (e.g., Atropine)',
  Anticonvulsants = 'Used for seizure control (e.g., Phenytoin, Valproate)',
  Anti_inflammatory_Agents = 'NSAIDs for inflammation (e.g., Ibuprofen, Naproxen)',
  Antimigraine_Agents = 'Treat migraines (e.g., Sumatriptan)',
  Antineoplastics = 'Cancer chemotherapy drugs (e.g., Doxorubicin, Cyclophosphamide)',
  Antiparasitics = 'Treat parasitic infections (e.g., Metronidazole, Ivermectin)',
  Beta_Blockers = 'Reduce blood pressure (e.g., Propranolol, Metoprolol)',
  Calcium_Channel_Blockers = 'Manage hypertension and angina (e.g., Amlodipine)',
  Immunomodulators = 'Modify immune responses (e.g., Interferons, Glatiramer acetate)',
  Opioid_Analgesics = 'Pain relief (e.g., Morphine, Fentanyl)',
  Thrombolytics = 'Break down blood clots (e.g., Alteplase)',
  Uricosurics = 'Manage gout (e.g., Allopurinol)',
  Antitubercular_Agents = 'Treat tuberculosis (e.g., Isoniazid, Rifampin)',
  Antiparkinson_Agents = 'Manage Parkinson’s disease (e.g., Levodopa, Carbidopa)',
  Bisphosphonates = 'Prevent bone density loss (e.g., Alendronate)',
  Contraceptives = 'Birth control (e.g., Ethinyl estradiol, Levonorgestrel)',
  Expectorants_and_Mucolytics = 'Facilitate mucus clearance (e.g., Guaifenesin, Acetylcysteine)',
  Gastrointestinal_Agents = 'Proton pump inhibitors and H2-receptor antagonists (e.g., Omeprazole, Ranitidine)',
  Hormone_Replacement_Therapy = 'Manage hormone deficiencies (e.g., Estradiol, Levothyroxine)',
  Hypoglycemics = 'Control blood sugar levels (e.g., Glipizide, Pioglitazone)',
  Antianginal_Agents = 'Used for chest pain management (e.g., Nitroglycerin)',
  Nootropics = 'Cognitive enhancers (e.g., Piracetam, Modafinil)',
  Antiglaucoma_Agents = 'Manage glaucoma (e.g., Timolol, Latanoprost)',
}
